<?php

namespace App\Filament\Resources\SupplyOrderResource\Pages;

use App\Enums\OrderStatus;
use App\Filament\Resources\SupplyOrderResource;
use Filament\Resources\Pages\CreateRecord;

class CreateSupplyOrder extends CreateRecord
{
    protected static string $resource = SupplyOrderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['status'] = OrderStatus::Pending;
        $data['created_by'] = auth()->id();

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
